name: destek_cepte
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.0 # Geniş uyumluluk için 3.0.0 yaptım

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0      # Firebase temeli
  firebase_auth: ^5.0.0      # Giriş/Kayıt işlemleri
  cloud_firestore: ^5.0.0    # Veritabanı
  # firebase_storage: ^12.0.0  <- Drive linki kullandığımız için sildim/kapattım
  # file_picker: ^8.0.0        <- Dosya seçmeyeceğimiz için sildim/kapattım
  url_launcher: ^6.2.0       # PDF/Drive linkine tıklayınca açmak için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Resimlerin çalışması için eklediğimiz kısım:
  assets:
    - assets/